version: 2.1

workflows:
  version: 2
  AWS:
    jobs:
      - Build
  #Azure:
    #jobs:
      #- Build
  Release testing:
    when:
      and:
        - equal: [ circleci-project-setup, << pipeline.git.branch >> ] #test merge to branch
    jobs:
      - Build
      - Hold:
          type: approval
          requires:
            - Build
      - Release:
          requires:
            - Build
            - Hold
jobs:
  Build:
    machine:
      image: ubuntu-2004:202104-01
    steps:
      - checkout
      - run: echo << pipeline.git.branch >>
      - setup-aws:
          BuildAWS: true
      - persist_to_workspace:
          root: .
          paths:
            - .
  Release:
    machine:
      image: ubuntu-2004:202104-01
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Configure AWS CLI
          command: |
            aws configure set aws_access_key_id ${AWS_ACCESS_KEY}
            aws configure set aws_secret_access_key ${AWS_SECRET_KEY}
      - run:
          name: Release Azure .zip
          command: |
            echo "Hello World"
            # ./.circleci/deployAzureZip.sh
commands:
  setup-aws:
      parameters:
        BuildAWS:
          description: ''
          type: boolean
          default: false
      steps:
        - when:
            condition:
              equal: [true, << parameters.BuildAWS >>]
            steps:
              - run:
                  name: Install Dependencies
                  command: |
                    cd /tmp
                    echo "Installing PowerShell Core"
                    wget -q https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
                    sudo apt-get install ./packages-microsoft-prod.deb
                    sudo apt update
                    sudo apt install powershell
                    pwsh --version
                    echo "Installing AWS SAM CLI"
                    wget -q https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip
                    unzip aws-sam-cli-linux-x86_64.zip -d sam-installation
                    sudo ./sam-installation/install
                    sam --version
                    echo "Installing .NET Core 3.1"
                    sudo apt-get update; \
                    sudo apt-get install -y apt-transport-https && \
                    sudo apt-get update && \
                    sudo apt-get install -y dotnet-sdk-3.1
              - run:
                  name: Install PowerShell Dependencies
                  shell: pwsh
                  command: |
                    Install-Module JumpCloud -Force
                    Install-Module AWSLambdaPSCore -Force
                    Install-Module AWS.Tools.Common -Force
                    Install-Module AWS.Tools.SecretsManager -Force
                    Install-Module AWS.Tools.SQS -Force
                    Get-InstalledModule
              - run:
                  name: Package AWS Serverless App
                  shell: pwsh
                  command: |
                    cd ./AWS
                    New-AWSPowerShellLambdaPackage -ScriptPath ./slack-parent.ps1 -OutputPackage slack-parent.zip
                    New-AWSPowerShellLambdaPackage -ScriptPath ./slack-child.ps1 -OutputPackage slack-child.zip
                    sam package --template-file template.yaml --output-template-file packaged.yaml --s3-bucket sa-circle-ci-lambda-package