version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202104-01
    steps:
      - run:
          name: Hello world
          command: echo "Hello, World!"
  release:
    machine:
      image: ubuntu-2004:202104-01
    steps:
      - run:
        name: Release Azure S3 .Zip
        command : ./deployAzureZip.sh
workflows:
  AWS:
    jobs:
      - build
  Azure:
    jobs:
      - build