version: 2.1

workflows:
  version: 2
  AWS:
    jobs:
      - Build
      - Setup AWS:
          requires:
            - Build
  #Azure:
    #jobs:
      #- Build
  Release testing:
    when:
      and:
        - equal: [ circleci-project-setup, << pipeline.git.branch >> ] #test merge to branch
    jobs:
      - Build
      - Hold:
          type: approval
          requires:
            - Build
      - Release:
          requires:
            - Build
            - Hold
jobs:
  Build:
    machine:
      image: ubuntu-2004:202104-01
    steps:
      - checkout
      - run: echo << pipeline.git.branch >>
      - persist_to_workspace:
          root: .
          paths:
            - .
  Release:
    machine:
      image: ubuntu-2004:202104-01
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Configure AWS CLI
          command: |
            aws configure set aws_access_key_id ${AWS_ACCESS_KEY}
            aws configure set aws_secret_access_key ${AWS_SECRET_KEY}
      - run:
          name: Release Azure .zip
          command: |
            echo "Hello World"
            # ./.circleci/deployAzureZip.sh
  Setup AWS:
    machine:
      image: ubuntu-2004:202104-01
    steps:
      - attach_workspace:
          at: .
      - setup-aws:
          BuildAWS: true
commands:
  setup-aws:
      parameters:
        BuildAWS:
          description: ''
          type: boolean
          default: false
      steps:
        - attach_workspace:
            at: .
        - when:
            condition:
              equal: [true, << parameters.BuildAWS >>]
            steps:
              - run:
                  name: Install PowerShell Core
                  command: |
                    cd /tmp
                    wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb
                    sudo apt-get install ./packages-microsoft-prod.deb
                    sudo apt update
                    sudo apt install powershell
                    pwsh --version
              - run:
                  name: Install PowerShell Dependencies
                  shell: pwsh
                  command: |
                    Install-Module JumpCloud -Force
                    Install-Module AWSLambdaPSCore -Force
                    Get-InstalledModule