version: 2.1
workflows:
  AWS:
    jobs:
      - build
  Azure:
    jobs:
      - build
jobs:
  build:
    machine:
      image: ubuntu-2004:202104-01
    steps:
      - run:
          name: Configure AWS CLI
          command: |
            aws configure set aws_access_key_id ${AWS_ACCESS_KEY}
            aws configure set aws_secret_access_key ${AWS_SECRET_KEY}
            aws sts get-caller-identity
