version: 2.1

build-and-release-azure: &build-and-release-azure
  - Build Slack App
  - Release Slack App:
      type: approval
      requires:
        - Build Slack App
  
workflows:
  version: 2
  AWS:
    jobs:
      - Build Slack App
  Azure:
    jobs:
      - *build-and-release-azure
jobs:
  Build Slack App:
    machine:
      image: ubuntu-2004:202104-01
    steps:
      - checkout
      - run:
          name: Configure AWS CLI
          command: |
            aws configure set aws_access_key_id ${AWS_ACCESS_KEY}
            aws configure set aws_secret_access_key ${AWS_SECRET_KEY}
      - persist_to_workspace:
          root: .
          paths:
            - .
  Release Slack App:
    machine:
      image: ubuntu-2004:202104-01
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Release Azure .zip
          command: |
            ls
            ./.circleci/deployAzureZip.sh